name = "watchlist"
main = "cloudflare-worker/src/index.ts"
compatibility_date = "2026-08-29"

# Serve React Frontend Static Assets (Single-Page App)
[assets]
directory = "./dist"
binding = "ASSETS"

# Bind Cloudflare D1 Database
[[d1_databases]]
binding = "frame_db"
database_name = "frame_db"
database_id = "148007ff-a587-4237-98a8-f72ca324c48c"
